Repository finapps/ruby-client, pull requests merged in 2022-01, with the labels that each got.

#282 Implement the Screening Metadata endpoints
  .rubocop.yml
  lib/finapps.rb
  lib/finapps/rest/client.rb
  lib/finapps/rest/screening_metadatas.rb
  spec/rest/screening_metadatas_spec.rb
  spec/support/fake_api.rb
  spec/support/fixtures/screening_metadatas/not_found.json
  spec/support/fixtures/screening_metadatas/show.json
  spec/support/routes/screening_metadatas.rb
Labels: enhancement, minor

#283 Fix bug in metadata body
  lib/finapps/rest/screening_metadatas.rb
Labels: bug

#284 Add operator names to term_array
  lib/finapps/rest/screenings.rb
  spec/rest/screenings_spec.rb
Labels: change, minor
